-- Abe Reads — Supabase schema
-- Run in the Supabase SQL editor, or: supabase db push
--
-- Anonymous auth is used so a child never needs an email address, while
-- row-level security still isolates every learner's rows.

create table if not exists public.progress (
  user_id     uuid        not null references auth.users (id) on delete cascade,
  pack_id     text        not null,
  page        int         not null default 1 check (page >= 1),
  stars       text[]      not null default '{}',
  pages_read  text[]      not null default '{}',
  updated_at  timestamptz not null default now(),
  primary key (user_id, pack_id)
);

create table if not exists public.quiz_results (
  id           bigint generated by default as identity primary key,
  user_id      uuid        not null references auth.users (id) on delete cascade,
  pack_id      text        not null,
  quiz_key     text        not null,
  score        int         not null check (score >= 0),
  total        int         not null check (total > 0),
  missed       text[]      not null default '{}',
  completed_at timestamptz not null default now()
);

create index if not exists quiz_results_user_idx
  on public.quiz_results (user_id, completed_at desc);

alter table public.progress      enable row level security;
alter table public.quiz_results  enable row level security;

-- Each learner sees and writes only their own rows.
drop policy if exists "own progress" on public.progress;
create policy "own progress" on public.progress
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own results" on public.quiz_results;
create policy "own results" on public.quiz_results
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Grown-up dashboard: per-quiz mastery for the signed-in learner.
create or replace view public.quiz_summary
with (security_invoker = true) as
select
  user_id,
  pack_id,
  quiz_key,
  count(*)                                            as attempts,
  max(round(100.0 * score / total))                    as best_pct,
  round(avg(100.0 * score / total))                    as avg_pct,
  max(completed_at)                                    as last_attempt
from public.quiz_results
group by user_id, pack_id, quiz_key;
